import { spawn } from 'node:child_process';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadSnapshot, sha256, jsonHash } from './check-lib.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, '../out');
const PORT = Number(process.env.AUDIT_PORT || 4180);
const LOCAL = `http://localhost:${PORT}/studyisc2/`;
const LIVE = 'https://cgdocx.github.io/studyisc2/';
const verifyLive = process.argv.includes('--verify-live');

let failed = 0;
const ok = (cond, msg) => { process.stdout.write((cond ? '[OK] ' : '[X] ') + msg + '\n'); if (!cond) failed++; };

// Every URL the legacy root site published, pinned (with checksums) when the legacy files were deleted.
const snap = loadSnapshot();
const SITE = Object.keys(snap.files);
const SAME_BYTES = SITE.filter(f => /\.csv$/.test(f));
const sameAsLegacy = (f, body) => sha256(body) === snap.files[f].sha256;
const SW_CACHE = 'studyisc2-cache-v4';
// manifest.json keeps every legacy field; only "icons" changed (pinned as a hash of the legacy JSON without icons).
const manifestFieldsKept = body => { const m = JSON.parse(body); delete m.icons; return jsonHash(m) === snap.files['manifest.json'].withoutIconsSha256; };

// Site icons (public/, generated by scripts/make-icons.mjs) and how they must look when served.
const ICONS = {
  'favicon.ico': { type: 'image/x-icon', sizes: [16, 32, 48] },
  'icon.svg': { type: 'image/svg+xml', sizes: [512] },
  'icon-192.png': { type: 'image/png', sizes: [192] },
  'icon-512.png': { type: 'image/png', sizes: [512] },
  'icon-maskable-512.png': { type: 'image/png', sizes: [512], opaque: true },
  'apple-touch-icon.png': { type: 'image/png', sizes: [180], opaque: true },
};
// <link> tags every page must carry (root layout metadata).
const PAGE_ICON_LINKS = ['icon /studyisc2/favicon.ico', 'icon /studyisc2/icon.svg', 'apple-touch-icon /studyisc2/apple-touch-icon.png'].sort();
const pageIconLinks = html => [...html.matchAll(/<link rel="(icon|apple-touch-icon)" href="([^"]+)"/g)].map(m => m[1] + ' ' + m[2]).sort();
// Square sizes actually encoded in an icon file, plus whether a PNG has no alpha channel.
function iconInfo(name, body) {
  const pngInfo = b => (b.length > 26 && b.readUInt32BE(0) === 0x89504e47 && b.readUInt32BE(12) === 0x49484452)
    ? { w: b.readUInt32BE(16), h: b.readUInt32BE(20), opaque: b[25] === 2 } : null;
  if (name.endsWith('.png')) { const i = pngInfo(body); return i && i.w === i.h ? { sizes: [i.w], opaque: i.opaque } : null; }
  if (name.endsWith('.ico')) {
    if (body.readUInt16LE(0) !== 0 || body.readUInt16LE(2) !== 1) return null;
    const sizes = [];
    for (let k = 0; k < body.readUInt16LE(4); k++) {
      const e = 6 + 16 * k, w = body[e] || 256, len = body.readUInt32LE(e + 8), off = body.readUInt32LE(e + 12);
      const i = pngInfo(body.subarray(off, off + len));
      if (!i || i.w !== w || i.h !== w) return null;
      sizes.push(w);
    }
    return { sizes: sizes.sort((a, b) => a - b) };
  }
  const vb = body.toString().match(/<svg[^>]*viewBox="0 0 (\d+) (\d+)"/);
  return vb && vb[1] === vb[2] ? { sizes: [Number(vb[1])] } : null;
}
const iconProblems = (name, r) => {
  const want = ICONS[name], info = r.status === 200 ? iconInfo(name, r.body) : null;
  if (r.status !== 200) return `${name} (${r.status})`;
  if (r.type !== want.type) return `${name} (type ${r.type})`;
  if (!info || info.sizes.join() !== want.sizes.join()) return `${name} (sizes ${info ? info.sizes.join('/') : 'unreadable'}, want ${want.sizes.join('/')})`;
  if (want.opaque && !info.opaque) return `${name} (has alpha; must be opaque)`;
  return null;
};

const lp = JSON.parse(readFileSync(resolve(here, '../src/data/content/learning-path.json'), 'utf8'));
const lpLinks = [...new Set(JSON.stringify(lp).match(/"link":"[^"]+"/g)?.map(s => s.slice(8, -1)) ?? [])];
const VARIANTS = [...new Set([
  '',
  ...SITE.filter(f => f.endsWith('.html')).map(f => f.replace(/\.html$/, '')).filter(f => f !== 'index'),
  ...[1, 2, 3, 4, 5].map(d => `flashcard.html?d=${d}`),
  ...lpLinks,
])].filter(v => !SITE.includes(v));

async function get(base, path) {
  try {
    const r = await fetch(base + path, { redirect: 'follow' });
    const body = Buffer.from(await r.arrayBuffer());
    return { status: r.status, type: (r.headers.get('content-type') || '').split(';')[0], body, url: r.url };
  } catch (e) {
    return { status: 0, type: '', body: Buffer.alloc(0), error: String(e) };
  }
}

if (verifyLive) {
  const bad = [];
  for (const f of SITE) {
    const r = await get(LIVE, f);
    if (r.status !== 200) { bad.push(`${f} (${r.status})`); continue; }
    if (f.endsWith('.html') && !r.body.toString().includes('/studyisc2/_next/')) bad.push(`${f} (not the Next.js build)`);
    if (SAME_BYTES.includes(f) && !sameAsLegacy(f, r.body)) bad.push(`${f} (bytes differ)`);
    if (f === 'manifest.json' && !manifestFieldsKept(r.body)) bad.push('manifest.json (fields other than icons differ from the legacy file)');
    if (f === 'sw.js' && !r.body.toString().includes(SW_CACHE)) bad.push(`sw.js (not the ${SW_CACHE} worker)`);
    if (f === 'index.html' && pageIconLinks(r.body.toString()).join() !== PAGE_ICON_LINKS.join()) bad.push('index.html (icon links missing)');
  }
  for (const name of Object.keys(ICONS)) { const p = iconProblems(name, await get(LIVE, name)); if (p) bad.push(p); }
  for (const v of VARIANTS) { const r = await get(LIVE, v); if (r.status !== 200) bad.push(`${v || '/'} (${r.status})`); }
  const asset = (await get(LIVE, 'index.html')).body.toString().match(/\/studyisc2\/(_next\/static\/[^"]+\.js)/);
  const assetRes = asset ? await get(LIVE, asset[1]) : { status: 0 };
  if (assetRes.status !== 200) bad.push(`_next asset ${asset ? asset[1] : '(none found)'} (${assetRes.status})`);
  ok(bad.length === 0, `live site ${LIVE}: ${SITE.length} site URLs and ${VARIANTS.length} URL forms return 200, every page is the Next.js build, _next/ assets load, sw.js is ${SW_CACHE}, ${Object.keys(ICONS).length} site icons load with the right type and size, manifest fields (apart from icons) and CSVs identical to the legacy files` + (bad.length ? ': ' + bad.join(', ') : ''));
  process.exit(failed ? 1 : 0);
}

const server = spawn(process.execPath, [resolve(here, 'serve-out.mjs')], { env: { ...process.env, PORT: String(PORT) }, stdio: ['ignore', 'pipe', 'inherit'] });
await new Promise((res, rej) => { server.stdout.once('data', res); server.once('exit', rej); });

try {
  ok(existsSync(OUT), 'out/ exists');
  process.stdout.write(`\nLegacy URL inventory pinned at ${snap.commit.slice(0, 7)}: ${SITE.length} site files\n\n`);

  const missing = [];
  for (const f of SITE) {
    const r = await get(LOCAL, f);
    const same = !SAME_BYTES.includes(f) || sameAsLegacy(f, r.body);
    if (r.status !== 200 || !same) missing.push(`${f} (${r.status}${same ? '' : ', bytes differ'})`);
  }
  ok(missing.length === 0, `${SITE.length} site URLs served from out/ at the same /studyisc2/ path (${SITE.filter(f => f.endsWith('.html')).length} pages, sw.js, manifest.json, ${SITE.filter(f => f.endsWith('.csv')).length} CSV byte-identical to the legacy files)` + (missing.length ? ': ' + missing.join(', ') : ''));

  const iconBad = [];
  for (const name of Object.keys(ICONS)) { const p = iconProblems(name, await get(LOCAL, name)); if (p) iconBad.push(p); }
  ok(iconBad.length === 0, `site icons: ${Object.entries(ICONS).map(([n, i]) => `${n} (${i.sizes.join('/')})`).join(', ')} return 200 from out/ with the right content type and encoded sizes; apple-touch and maskable icons are opaque` + (iconBad.length ? ': ' + iconBad.join(', ') : ''));
  const noIcons = [];
  for (const f of SITE.filter(f => f.endsWith('.html'))) { const links = pageIconLinks((await get(LOCAL, f)).body.toString()); if (links.join() !== PAGE_ICON_LINKS.join()) noIcons.push(`${f} (${links.join(', ') || 'none'})`); }
  ok(noIcons.length === 0, `every one of ${SITE.filter(f => f.endsWith('.html')).length} pages links ${PAGE_ICON_LINKS.join(', ')}` + (noIcons.length ? ': ' + noIcons.slice(0, 5).join('; ') : ''));

  const badVariants = [];
  for (const v of VARIANTS) { const r = await get(LOCAL, v); if (r.status !== 200 || r.type !== 'text/html') badVariants.push(`${v || '/'} (${r.status})`); }
  ok(badVariants.length === 0, `${VARIANTS.length} extra URL forms resolve: /studyisc2/, extensionless page URLs, flashcard.html?d=1..5, learning-path step links` + (badVariants.length ? ': ' + badVariants.join(', ') : ''));

  const noSlash = await fetch(`http://localhost:${PORT}/studyisc2`, { redirect: 'manual' });
  ok(noSlash.status === 302 && noSlash.headers.get('location') === '/studyisc2/', '/studyisc2 redirects to /studyisc2/ (as GitHub Pages does)');

  const sw = readFileSync(resolve(OUT, 'sw.js'), 'utf8');
  const pre = sw.match(/PRECACHE_ASSETS = \[([\s\S]*?)\]/)[1].match(/'[^']+'/g).map(s => s.slice(1, -1));
  const preBad = [];
  for (const p of pre) { const r = await get(LOCAL, p.replace(/^\.\//, '')); if (r.status !== 200) preBad.push(`${p} (${r.status})`); }
  ok(preBad.length === 0, `sw.js: all ${pre.length} precache entries resolve under /studyisc2/ (${pre.join(' ')})` + (preBad.length ? ': ' + preBad.join(', ') : ''));
  ok(sw.includes(`const CACHE_NAME = '${SW_CACHE}';`) && pre.includes('./favicon.ico'), `sw.js: cache ${SW_CACHE} and favicon.ico back in the precache list`);

  const man = JSON.parse(readFileSync(resolve(OUT, 'manifest.json'), 'utf8'));
  const manUrl = new URL('manifest.json', LOCAL);
  const start = new URL(man.start_url, manUrl), scope = new URL(man.scope, manUrl);
  const startRes = await get('', start.href);
  ok(startRes.status === 200 && scope.pathname === '/studyisc2/' && start.pathname.startsWith(scope.pathname), `manifest.json: start_url -> ${start.pathname} (200), scope -> ${scope.pathname}`);
  const manRaw = readFileSync(resolve(OUT, 'manifest.json'));
  ok(manifestFieldsKept(manRaw), 'manifest.json: every field except icons identical to the legacy file');
  const manBad = [];
  for (const k of ['name', 'short_name', 'start_url', 'display']) if (typeof man[k] !== 'string' || !man[k]) manBad.push(`missing ${k}`);
  for (const i of man.icons) {
    const u = new URL(i.src, manUrl), name = u.pathname.replace('/studyisc2/', '');
    if (!u.pathname.startsWith('/studyisc2/') || !ICONS[name]) { manBad.push(`${i.src} (not a site icon under /studyisc2/)`); continue; }
    if (i.type !== ICONS[name].type) manBad.push(`${i.src} (type ${i.type})`);
    const declared = i.sizes === 'any' ? 'any' : i.sizes.split(/\s+/).map(s => { const [w, h] = s.split('x').map(Number); return w === h ? w : NaN; }).sort((a, b) => a - b).join('/');
    if (declared !== (name.endsWith('.svg') ? 'any' : ICONS[name].sizes.join('/'))) manBad.push(`${i.src} (sizes "${i.sizes}")`);
    const p = iconProblems(name, await get('', u.href));
    if (p) manBad.push(p);
  }
  const png = (size, purpose) => man.icons.some(i => i.type === 'image/png' && i.sizes === `${size}x${size}` && (i.purpose || 'any').split(' ').includes(purpose));
  if (!png(192, 'any') || !png(512, 'any')) manBad.push('needs 192x192 and 512x512 PNG icons (purpose any)');
  if (!png(512, 'maskable')) manBad.push('needs a 512x512 maskable PNG');
  ok(manBad.length === 0, `manifest.json: valid for install (name, short_name, start_url, display; ${man.icons.length} icons all under /studyisc2/, 200, declared type and sizes match the files; 192 and 512 PNG plus maskable 512)` + (manBad.length ? ': ' + manBad.join(', ') : ''));

  const seen = new Map();
  const queue = ['', ...SITE.filter(f => f.endsWith('.html')), ...VARIANTS];
  const broken = [];
  let nextAssets = 0;
  while (queue.length) {
    const path = queue.shift();
    if (seen.has(path)) continue;
    const r = await get(LOCAL, path);
    seen.set(path, r.status);
    if (r.status !== 200) { broken.push(`${path || '/'} (${r.status})`); continue; }
    if (path.startsWith('_next/')) nextAssets++;
    if (r.type !== 'text/html') continue;
    const html = r.body.toString('utf8');
    const refs = [...html.matchAll(/\s(?:href|src)="([^"]+)"/g)].map(m => m[1])
      .concat([...html.matchAll(/\ssrcset="([^"]+)"/g)].flatMap(m => m[1].split(',').map(s => s.trim().split(/\s+/)[0])));
    for (const ref of refs) {
      if (/^(https?:|mailto:|tel:|data:|javascript:|#)/.test(ref) || ref.includes('${')) continue;
      const u = new URL(ref.replace(/&amp;/g, '&'), new URL(path, LOCAL));
      if (u.origin !== new URL(LOCAL).origin) continue;
      if (!u.pathname.startsWith('/studyisc2/') && u.pathname !== '/studyisc2') { broken.push(`${u.pathname} (outside basePath, from ${path || '/'})`); continue; }
      const rel = u.pathname === '/studyisc2' ? '' : u.pathname.slice('/studyisc2/'.length) + u.search;
      if (!seen.has(rel)) queue.push(rel);
    }
  }
  ok(broken.length === 0, `link crawl: ${seen.size} internal URLs reachable from every page all return 200, including ${nextAssets} _next/ assets` + (broken.length ? ': ' + broken.slice(0, 10).join(', ') : ''));

  const outFiles = readdirSync(OUT, { recursive: true, withFileTypes: true }).filter(d => d.isFile()).map(d => resolve(d.parentPath, d.name).slice(OUT.length + 1));
  const outBad = [];
  for (const f of outFiles) { const r = await get(LOCAL, f.split('/').map(encodeURIComponent).join('/')); if (r.status !== 200) outBad.push(`${f} (${r.status})`); }
  const under = outFiles.filter(f => f.split('/').some(p => p.startsWith('_')));
  ok(outBad.length === 0, `all ${outFiles.length} files in out/ are served, including ${under.length} under underscore paths (_next/, __next.*.txt, which a Jekyll build would drop) and ${outFiles.filter(f => f.startsWith('data/')).length} runtime question banks in data/` + (outBad.length ? ': ' + outBad.slice(0, 10).join(', ') : ''));

  const notFound = await get(LOCAL, 'no-such-page.html');
  ok(notFound.status === 404 && notFound.body.toString().includes('/studyisc2/_next/'), 'unknown URL returns 404 with the exported 404.html');

} finally {
  server.kill();
}
process.exit(failed ? 1 : 0);
